name: Update Readme

on:
  schedule:
    - cron: '15 */12 * * *'
  workflow_dispatch:
  
jobs:
  wakatime-metrics:
    name: Update WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "docs: update wakatime metrics"
          SHOW_UPDATED_DATE: "true"
          UPDATED_DATE_FORMAT: "%a, %e %b %Y %T %Z"
          SHOW_LINES_OF_CODE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_COMMIT: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LOC_CHART: "true"
